[package]
name = "lantern-wasi"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[[bin]]
name = "lantern"
path = "src/main.rs"

[dependencies]
pumpkin = { path = "../../pumpkin/pumpkin" }
pumpkin-config = { path = "../../pumpkin/pumpkin-config" }
pumpkin-util = { path = "../../pumpkin/pumpkin-util" }
tokio = { version = "1.53", default-features = false, features = ["macros", "rt"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
wasi = "0.11"
